version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: node-mongodb-app
    env_file: ./.env
    container_name: nodebackend2
    ports:
      - $PROXY_PORT:$PROXY_PORT
      - $REPORT_SERVICE_PORT:$REPORT_SERVICE_PORT
    volumes: 
      - ./src:/src
      - /node_modules
    depends_on:
      - mongodb
  mongodb:
    image: mongo:4
    command: mongod
    ports:
      - "27017:27017"
    container_name: dbmongo